apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: website
  app.kubernetes.io/part-of: website
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
