#!/bin/bash

STORE=https://gitlab.com/Harmelodic/bp-frontend/raw/master/files
PROJECT_NAME=`basename $PWD`

mkdir k8s
mkdir public
mkdir src
mkdir src/components
mkdir src/containers
mkdir src/redux

echo "Loading... README.md"
curl -s $STORE/README.md | sed -e "s|PROJECT_NAME|$PROJECT_NAME|" > README.md

echo "Loading... Config & Build Files"
curl -s $STORE/.eslintrc.yml -O
curl -s $STORE/.gitignore -O
curl -s $STORE/.gitlab-ci.yml -O
curl -s $STORE/CONTRIBUTING.md -O
curl -s $STORE/Dockerfile -O
curl -s $STORE/nginx.conf -O
curl -s $STORE/package.json -O
curl -s $STORE/webpack.config.js -O
curl -s $STORE/webpack.dev.js -O
curl -s $STORE/webpack.prod.js -O

echo "Loading... K8s Files"
cd k8s
curl -s $STORE/k8s/deployment.yml -O
curl -s $STORE/k8s/ingress.yml -O
curl -s $STORE/k8s/service.yml -O
cd ..

echo "Loading... Output Files"
cd public
curl -s $STORE/public/index.html -O
curl -s $STORE/public/health -O
cd ..

echo "Loading... Application Code"
cd src/components
curl -s $STORE/src/components/Title.js -O
cd ../containers
curl -s $STORE/src/containers/App.js -O
curl -s $STORE/src/containers/Index.js -O
cd ../redux
curl -s $STORE/src/redux/Actions.js -O
curl -s $STORE/src/redux/Middleware.js -O
curl -s $STORE/src/redux/Reducers.js -O
curl -s $STORE/src/redux/Store.js -O
cd ..
curl -s $STORE/src/index.js -O
cd ..

# Install Dependencies
npm init -y
npm i -D \
    @babel/core \
    @babel/preset-react \
    babel-loader \
    babel-minify-webpack-plugin \
    compression-webpack-plugin \
    eslint \
    eslint-config-google \
    eslint-plugin-react \
    react \
    react-dom \
    react-router-dom \
    redux \
    redux-thunk \
    styled-components \
    webpack \
    webpack-cli \
    webpack-dev-server \
    webpack-merge

npm run lint

# Git init
git init
git add .
git commit -m "Initial Commit"


# Boot
if [ -x "$(command -v code)" ]; then
    code .
    npm start
fi
