apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.APP_NAME}}
  namespace: {{.KUBE_NAMESPACE}}
  labels:
    app: {{.APP_NAME}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{.INGRESS_HOST}}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{.APP_NAME}}
            servicePort: 80
