apiVersion: v1
kind: Service
metadata:
  name: {{.APP_NAME}}
  labels:
    app: {{.APP_NAME}}
spec:
  ports:
  - name:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.APP_NAME}}
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}